File navigation improvements
jurplel/qView pull request #529
Opened 2022-11-25 18:02 UTC by jdpurcell

While trying to reproduce #472, I noticed it was already fixed by my previous optimization work. However, the optimizations introduced a new quirk in which the folder file count (e.g. when "Practical" titlebar text is enabled) didn't update immediately after deleting a file. I fixed that here, and also made it more robust to deleted files in general. For example, say you're viewing the 5th file in some folder, and files # 4 and 5 get deleted externally (e.g. via Finder/Explorer). Navigating to previous file now handles that gracefully and loads up file # 3.

This also adds the ability to drag a folder onto the qView window as discussed in #479. Thought I'd kill two birds with one stone, since there is some overlap in the code.

**Marked as draft because this branch contains a bunch of noise from other changes.** Since it builds on previous work, it's based on my `combined` branch. If/when #517 and #526 get merged, I will rebase this onto master.

2022-12-24 17:48 UTC, jdpurcell commented
Rebased on current master, ready for review. I can't remember if splitting out into the new `sortCompatibleFiles` function was entirely necessary, but I went through a lot of iterations when developing this and it definitely helped me reason about the code better having it separated out. If you aren't a fan of that refactoring, let me know and I'll see if it's possible to back it out.

As for the build error, maybe that was just a random error that goes away after retrying? The same commit [built fine](https://github.com/jdpurcell/qView/actions/runs/3772317628) on my repo.

2022-12-27 21:27 UTC, jurplel requested changes

2022-12-27 21:27 UTC, jurplel commented on src/qvgraphicsview.cpp
> +        const auto &fileList = getCurrentFileDetails().folderFileInfoList;
Could move fileList outside of the if block and use it below I believe

2022-12-27 21:27 UTC, jurplel commented on src/qvimagecore.cpp
> +    baseRandomSortSeed = std::chrono::system_clock::now().time_since_epoch().count();
As discussed, I believe the old approach is ok, and I believe it should rescramble every time the folder is re-opened.

2022-12-27 21:27 UTC, jurplel commented on src/qvimagecore.cpp
> +        QString dummyFilePath = QDir::cleanPath(sanitaryFileName + QDir::separator() + "dummy.jpg");
Can you write a comment explaining the use of dummy.jpg a little? I get it but just to make it more readable

2022-12-28 00:30 UTC, jdpurcell commented
@jurplel The suggested changes were made and I got rid of that dummy.jpg thing as well, I realized it's cleaner to make `updateFolderInfo` take a folder instead of a file path.

2022-12-28 20:02 UTC, jurplel approved these changes

2022-12-28 20:02 UTC, merged